[project]
name = "hand-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvzone>=1.6.1",
    "mediapipe>=0.10.31",
    "python-osc>=1.9.3",
]
